caoyingjunz/pixiu

api/server/router/cloud/cloud.go
api/server/router/cloud/cloud_routes.go
pkg/core/cloud.go

add kubernetes deployment delete

---

cmd/app/options/options.go
config.yaml
pkg/log/logging.go
pkg/util/util.go

新增一个checkDir函数
在logging初始化的时候，去判断目录是否存在，如果存在直接通过，不存在则执行创建目录

在log_dir目录不存在的情况下，自动创建,将初始化的log路径设置为/var/log/pixiu

---

api/server/router/cloud/cloud.go
api/server/router/cloud/cloud_routes.go
pkg/core/cloud.go
pkg/core/cloud_kubernetes.go

Signed-off-by: Fang Yuan <wojiushifangyuanlove@gmail.com>
#87

Adding, deleting and checking of statefulset

---

cmd/app/options/options.go
cmd/app/server.go

Complete run graceful pixiu server

---

api/server/router/cloud/cloud_routes.go
api/types/types.go
pkg/core/cloud.go
pkg/db/cloud/cloud.go

[ADD] 添加cloud分页查询

---

api/server/router/cicd/cicd_routes.go
api/types/types.go
pkg/core/cicd.go
pkg/types/types.go

jenkins支持创建：
-- 自由风格Job
重新定义xml模板文件，支持giturl等变量传入
-- Pipline风格Job
重新定义xml模板文件，支持giturl等变量传入

Chx createjob

---

docs/sql.md

change user and password to gopixiu

A PR Update sql.md

---

api/server/router/cloud/cloud.go
api/server/router/cloud/deployment_routes.go
pkg/core/kubernetes/deployment.go

add deployment update route

---

api/server/router/menu/menu_routers.go
api/server/router/role/role_routes.go
api/types/menus.go
pkg/core/menu.go
pkg/core/role.go
pkg/core/user.go
pkg/db/model/menu.go
pkg/db/user/authentication.go
pkg/db/user/menu.go
pkg/db/user/role.go
pkg/db/user/user.go

1、修复判断角色是否存在bug
2、修复判断权限是否存在bug
3、增加code字段用于前端权限判断

fix some bug

---

pkg/core/core.go

Clean up useless code core.go clientSets map[string]*kubernetes.Clientset

[fix] Clean up useless code

---

api/meta/types.go
api/server/router/user/user.go
api/server/router/user/user_routes.go
pkg/core/user.go
pkg/db/user/user.go
pkg/types/constant.go

Co-authored-by: “HoHenSer” <“1451571361@qq.com”>
Co-authored-by: caoyingjunz <cao.yingjunz@gmail.com>

Add resetpassword api supported

---

api/server/router/router.go
cmd/app/config/config.go
cmd/app/options/options.go
config.yaml

enable: false时，不注册 CICD driver

增加CICD driver 组件的开关

---

README.md
api/server/middleware/middleware.go

Fixes #
```release-note
```
```docs
```

Disable Authentication when use debug mode

---

api/server/middleware/middleware.go
api/server/router/proxy/proxy.go
pkg/cache/store.go
pkg/core/cloud.go

Fixes #
```release-note
```
```docs
```

Get kubeconfig obj from cache store for kube-proxy APIs

---

Makefile

/kind documentation
fix a word spelling
Fixes #
```release-note
```
```docs
```

fix(doc): fix a word spelling

---

.github/workflows/docker-image.yml
cmd/app/options/options.go

Fixes #
```release-note
```
```docs
```

Update the defaultConfigFile path

---

deploy/pixiu/templates/deployment.yaml

Fixes #
```release-note
```
```docs
```

Fix helm chart install failed

---

pkg/core/cloud.go

修复新导入集群进入出现cluster not register问题
修复集群节点数始终为1问题

To fix cluster not register

---

api/server/router/cloud/cloud_routes.go
api/types/types.go
cmd/app/server.go
pkg/core/cloud.go
pkg/types/constant.go
pkg/util/kubernetes.go

Fixes #
```release-note
```
```docs
```

Refacotr create cloud APIs

---

api/server/router/proxy/proxy.go
pkg/core/cloud.go

Fixes #
```release-note
```
```docs
```

Add syncStatus func to update cloud status

---

api/types/types.go
pkg/core/cloud.go
pkg/types/types.go

Fixes #
```release-note
```
```docs
```

update pkg/core/cloud.go process func

---

api/server/router/router.go

Fixes #
```release-note
```
```docs
```

调整 http 路由注册方式

---

api/server/router/cluster/cluster.go
api/server/router/cluster/cluster_routes.go
cmd/app/config/config.go
cmd/app/options/options.go
cmd/app/server.go
cmd/pixiuserver.go
config.yaml
pkg/controller/cluster/cluster.go
pkg/types/types.go

Fixes #
```release-note
```
```docs
```

实现k8s cluster 的常规接口（包括 pinger）

---

api/server/router/cluster/cluster_routes.go
pkg/controller/cluster/cluster.go

Fixes #
```release-note
```
```docs
```

Completed pinger API interface

---

api/server/router/proxy/proxy.go
api/server/router/router.go
api/server/router/user/user.go
api/server/router/user/user_router.go
pkg/controller/cluster/cluster.go
pkg/controller/controller.go
pkg/controller/user/user.go
pkg/controller/user/user_test.go
pkg/db/model/model.go
pkg/db/user.go
pkg/types/types.go

Fixes #
```release-note
```
```docs
```

Completed the user crud APIs

---

api/server/middleware/authentication.go
api/server/middleware/limiter.go
api/server/middleware/middleware.go
cmd/app/config/config.go
config.yaml
docs/sql.md
pkg/controller/user/user.go
pkg/types/types.go
pkg/util/lru/lru.go
pkg/util/util.go

Fixes #
```release-note
```
```docs
```

优化中间件用户限速的部分代码

---

api/server/router/user/user.go
docs/README.md
pkg/controller/user/user.go

Fixes #
```release-note
```
```docs
```

优化登陆日志，填充初始账号信息

---

docs/sql.md
pkg/controller/cluster/cluster.go
pkg/db/model/model.go
pkg/types/types.go

0：标准集群 1: 自建集群
Fixes #
```release-note
```
```docs
```

支持 k8s 集群类型的识别和数据获取

---

api/docs/docs.go
api/docs/swagger.json
api/docs/swagger.yaml
api/server/router/cluster/cluster_routes.go
api/server/router/router.go
api/server/router/user/user_router.go
cmd/pixiuserver.go

Add APIs doc server for pixiu

---

api/docs/docs.go
api/docs/swagger.json
api/docs/swagger.yaml
api/server/router/cluster/cluster.go
api/server/router/router.go
cmd/pixiuserver.go
pkg/controller/cluster/cluster.go
pkg/util/uuid/uuid.go

Fixes #
```release-note
```
```docs
```

调整 kubernetes API ping 接口

---

api/server/router/cluster/cluster.go
api/server/router/cluster/cluster_routes.go
pkg/controller/cluster/cluster.go
pkg/types/meta.go
pkg/types/types.go

Fixes #
```release-note
```
```docs
```

Add AggregateEvents supported

---

config.yaml
pkg/controller/cluster/cluster.go

Fixes #
```release-note
```
```docs
```

Fix event insert chan failed

---

pkg/controller/cluster/cluster.go

优化 cpu 和 memory 格式提升可读性

---

api/server/router/cluster/cluster.go
api/server/router/cluster/helm_routes.go
api/server/router/helm/helm.go
pkg/controller/cluster/cluster.go
pkg/controller/cluster/helm.go

Fixes #
```release-note
```
```docs
```

Add list helm releases API supported

---

.gitignore
api/server/router/cluster/cluster.go
api/server/router/cluster/ws.go
go.mod
go.sum
pkg/controller/cluster/cluster.go
pkg/types/meta.go
pkg/types/types.go

Fixes #
```release-note
```
```docs
```

Add kubernetes pod webshell supported

---

docs/sql.md
pkg/controller/cluster/cluster.go
pkg/db/model/model.go
pkg/types/types.go

Fixes #
```release-note
```
```docs
```

Add cluster protected interface

---

Dockerfile
Makefile

Fixes #
```release-note
```
```docs
```

Fix webshell image build failed

---

.github/workflows/docker-image.yml

/kind feature
Building multi-arch images support x64 and aarch64 platform.
```release-note
NONE
```

Publish multi-arch images to DockerHub with CI

---

.github/workflows/build-webshell-image.yml

/kind feature
Building webshell image when Dockerfile or Makefile is updated only, for saving time and resources.
```release-note
NONE
```

Reducing Unnecessary building in CI

---

cmd/app/config/config.go
cmd/app/options/options.go
config.yaml
pkg/db/cluster.go
pkg/db/migrator.go

Fixes #
```release-note
```
```docs
```

Add table created automatically supported

---

api/server/httputils/httputils.go
api/server/middleware/authentication.go
api/server/router/user/user_routes.go
pkg/controller/user/user.go
pkg/db/migrator.go
pkg/db/model/model.go
pkg/db/user.go
pkg/types/types.go

Fixes #
```release-note
```
```docs
```

支持首个用户的注册流程

---

api/server/errors/errors.go
api/server/httputils/httputils.go
api/server/router/user/user_routes.go
pkg/controller/user/user.go
pkg/types/request.go

/kind feature
Validate login request body with gin binding module.
```release-note
NONE
```

Validate login request body

---

pkg/db/cluster.go
pkg/db/migrator.go
pkg/db/model/cluster.go
pkg/db/model/node.go
pkg/db/model/tenant.go
pkg/db/model/user.go
pkg/db/tenant.go
pkg/db/user.go

/kind feature
Migrating tenant table when running
```release-note
NONE
```

Migrate tenant table

---

api/server/errors/errors.go
pkg/controller/user/user.go
pkg/db/user.go
pkg/types/request.go
pkg/util/errors/errors.go

/kind feature
Raw database errors should not be exposed to users.
```release-note
NONE
```

Do not expose raw db errors

---

api/server/errors/errors.go
api/server/router/cluster/cluster_routes.go
api/server/router/user/user_routes.go
pkg/controller/cluster/cluster.go
pkg/controller/user/user.go
pkg/db/cluster.go
pkg/db/model/cluster.go
pkg/db/user.go
pkg/types/request.go
pkg/types/types.go
pkg/util/errors/errors.go

/kind feature
1. Validate cluster create request body with gin binding module.
2. Create cluster entry in transaction gracefully.
```release-note
NONE
```

Validate cluster create request body

---

api/server/errors/errors.go
api/server/router/tenant/tenant_routes.go
pkg/controller/cluster/cluster.go
pkg/controller/tenant/tenant.go
pkg/db/cluster.go
pkg/db/tenant.go
pkg/types/request.go
pkg/util/errors/errors.go

/kind feature
Validate tenant create request body with gin binding module.
```release-note
NONE
```

Validate tenant create request body

---

api/server/router/cluster/cluster.go
api/server/router/cluster/cluster_routes.go
pkg/controller/cluster/cluster.go
pkg/db/cluster.go
pkg/types/request.go

Fixes #
```release-note
```
```docs
```

Add protect cluster API supported

---

api/server/validator/validator.go
pkg/controller/cluster/cluster.go
pkg/controller/tenant/tenant.go
pkg/db/model/pixiu/model.go
pkg/types/request.go

/kind bug
Fixed resource version validation error when the value is `0`.
```release-note
NONE
```

Fixed resource version validation error

---

api/server/errors/errors.go
api/server/httputils/httputils.go
api/server/validator/helper.go
api/server/validator/password.go
api/server/validator/validator.go
go.mod

/kind feature
Return human readable validation error.
1. `required` validation error:
```json
{"code":400,"message":"New为必填字段; Old为必填字段"}
```
2. `password` validation error:
```json
{"code":400,"message":"New密码强度不够，至少包含一个大写字母、一个小写字母、一个数字"}
```
3. `email` validation error:
```json
{"code":400,"message":"Email必须是一个有效的邮箱"}
```

Translate validation error

---

api/server/validator/password.go
api/server/validator/validator.go

Fixes #
```release-note
```
```docs
```

微调自定义validator的实现方式

---

pkg/controller/user/user.go
pkg/types/request.go

Fixes #
```release-note
```
```docs
```

登陆时新增用户id返回

---

pkg/controller/user/user.go
pkg/types/request.go

Fixes #
```release-note
```
```docs
```

Add user role into login response

---

api/server/middleware/authentication.go
api/server/middleware/authorization.go
api/server/middleware/middleware.go
pkg/types/request.go

Fixes #
```release-note
```
```docs
```

修复用户注册页面跳转异常

---

pkg/db/migrator.go

Fixes #
```release-note
```
```docs
```

Optimization for Create Tables Func

---

api/server/httputils/httputils.go
api/server/middleware/authorization.go
pkg/controller/user/user.go
pkg/types/request.go

Fixes #
```release-note
```
```docs
```

Add reset password API supported

---

api/server/router/plan/plan.go
api/server/router/plan/plan_routes.go
api/server/router/router.go
pkg/controller/controller.go
pkg/controller/plan/plan.go
pkg/db/factory.go
pkg/db/model/plan.go
pkg/db/plan.go
pkg/types/request.go
pkg/types/types.go

Fixes #
```release-note
```
```docs
```

Add deploy plan API supported

---

api/server/router/plan/plan.go
api/server/router/plan/plan_routes.go
cmd/app/server.go
pkg/controller/plan/plan.go
pkg/controller/plan/worker.go
pkg/db/model/plan.go
pkg/db/plan.go
pkg/types/request.go
pkg/types/types.go

Fixes #
```release-note
```
```docs
```

[part3] Complated plan's config APIs

---

pkg/controller/plan/plan.go
pkg/controller/plan/worker.go
pkg/db/model/plan.go
pkg/db/plan.go

Fixes #
```release-note
```
```docs
```

 [part4] Complated plan's  deployment APIs

---

api/server/middleware/authentication.go
config.yaml

Fixes #
```release-note
```
```docs
```

debug 模式下不进行单点登陆验证

---

pkg/controller/plan/worker.go
template/globals.go
template/hosts.go
template/multinode.go

Fixes #
```release-note
```
```docs
```

[part1] Completed pixiu plan config render

---

go.mod
pkg/controller/plan/bootstrap_servers.go
pkg/controller/plan/checker.go
pkg/controller/plan/render.go
pkg/controller/plan/worker.go
pkg/db/plan.go
pkg/util/container/container.go
pkg/util/errors/errors.go
pkg/util/util.go
template/globals.go
template/hosts.go
template/multinode.go

Fixes #
```release-note
```
```docs
```

[part2] Completed pixiu plan config render

---

pkg/controller/plan/bootstrap_servers.go
pkg/controller/plan/render.go
pkg/util/container/container.go
template/hosts.go

Fixes #
```release-note
```
```docs
```

[part3] Completed pixiu plan config render

---

api/server/router/plan/plan.go
api/server/router/plan/task_routes.go
pkg/controller/plan/plan.go
pkg/controller/plan/plan_task.go
pkg/controller/plan/worker.go
pkg/db/plan.go
pkg/types/types.go

Fixes #
```release-note
```
```docs
```

Completed plan task API

---

pkg/controller/plan/plan_node.go
pkg/controller/plan/render.go
pkg/db/model/plan.go
pkg/types/request.go
pkg/types/types.go
template/multinode.go

Fixes #
```release-note
```
```docs
```

Completed multinode render Func

---

pkg/controller/plan/plan.go
pkg/controller/plan/render.go
pkg/controller/plan/worker.go
pkg/db/model/plan.go
pkg/db/plan.go
pkg/types/types.go
pkg/util/util.go

Fixes #
```release-note
```
```docs
```

优化task的状态同步

---

pkg/controller/plan/render.go
pkg/types/types.go
template/multinode.go

Fixes #
```release-note
```
```docs
```

新增节点的rsa内容渲染

---

api/server/errors/errors.go
pkg/controller/plan/plan.go
pkg/util/errors/errors.go

Fixes #
```release-note
```
```docs
```

Add deployment plan validation functionality

---

pkg/controller/plan/bootstrap_servers.go
pkg/controller/plan/checker.go
pkg/controller/plan/deploy.go
pkg/controller/plan/render.go
pkg/controller/plan/worker.go
pkg/types/types.go
template/globals.go

Fixes #
```release-note
```
```docs
```

新增global配置渲染实现

---

pkg/controller/plan/deploy.go
pkg/controller/plan/worker.go
pkg/util/container/container.go
template/globals.go

Fixes #
```release-note
```
```docs
```

优化部署任务进度状态

---

install.md

Fixes #
```release-note
```
```docs
```

Update the pixiu-aio image repo

---

cmd/app/config/config.go
cmd/app/options/options.go
config.yaml
pkg/controller/plan/render.go

Fixes #
```release-note
```
```docs
```

Add the configuration of workDir

---

cmd/app/options/options.go
config.yaml
install.md
pkg/util/container/container.go

Fixes #
```release-note
```
```docs
```

支持 API 部署 kubernetes 集群

---

cmd/app/options/options.go
config.yaml
install.md
pkg/util/container/container.go

Fixes #
```release-note
```
```docs
```

Optimise the workDir to /etc/pixiu

---

pkg/controller/plan/plan_config.go

Fixes #
```release-note
```
```docs
```

修复部署配置首次创建即冲突的问题

---

install.md

Fixes #
```release-note
```
```docs
```

Update  image registry to install.md

---

cmd/app/config/config.go
cmd/app/options/options.go
config.yaml
install.md
pkg/controller/plan/bootstrap_servers.go
pkg/controller/plan/deploy.go
pkg/controller/plan/worker.go
pkg/util/container/container.go

Fixes #
```release-note
```
```docs
```

Add plan deploy worker images supported

---

cmd/app/config/config.go
config.yaml
pkg/controller/plan/bootstrap_servers.go
pkg/controller/plan/deploy.go
pkg/controller/plan/plan.go
pkg/controller/plan/plan_config.go
pkg/controller/plan/render.go
pkg/controller/plan/worker.go
pkg/db/model/plan.go
pkg/types/request.go
pkg/types/types.go
pkg/util/container/container.go

Fixes #
```release-note
```
```docs
```

新增虚拟机操作系统标识

---

.github/workflows/docker-image.yml

/kind ci
Update github workflows for pushing images to pixiuio harbor registry.
```release-note
NONE
```

Push images to pixiuio harbor registry

---

api/server/router/plan/plan.go
api/server/router/plan/plan_routes.go
pkg/controller/plan/plan.go
pkg/controller/plan/plan_config.go
pkg/controller/plan/plan_node.go
pkg/controller/plan/render.go
pkg/db/model/plan.go
pkg/db/plan.go
pkg/types/meta.go
pkg/types/request.go
pkg/types/types.go

Fixes #
```release-note
```
```docs
```

Merged plan config and node into plan APIs

---

pkg/controller/plan/plan.go
pkg/controller/plan/plan_config.go
pkg/controller/plan/plan_node.go
pkg/db/model/plan.go
pkg/db/plan.go
pkg/types/request.go

Fixes #
```release-note
```
```docs
```

支持plan的update APIs

---

pkg/controller/plan/plan_config.go
pkg/controller/plan/plan_node.go

Fixes #
```release-note
```
```docs
```

Fix region missing

---

pkg/controller/plan/plan_config.go
pkg/controller/plan/plan_node.go

Fixes #
```release-note
```
```docs
```

Fix create new node failed

---

api/server/router/plan/plan.go
api/server/router/plan/plan_routes.go
api/server/router/plan/task_routes.go
pkg/client/task.go
pkg/controller/plan/plan.go
pkg/controller/plan/plan_task.go
pkg/controller/plan/worker.go
pkg/db/plan.go

Fixes #
```release-note
```
```docs
```

支持task状态的实时同步

---

install.md

Fixes #
```release-note
```
```docs
```

Modify install.md Part of the explanation

---

pkg/controller/plan/worker.go
pkg/db/plan.go

Fixes #
```release-note
```
```docs
```

Complete task start and end time

---

.github/workflows/ci.yml

Fixes #
```release-note
```
```docs
```

Fix markdown-lint ci failed

---

api/server/router/plan/plan_routes.go
config.yaml
pkg/controller/plan/plan.go
pkg/controller/plan/plan_config.go
pkg/controller/plan/plan_node.go
pkg/controller/plan/render.go
pkg/db/model/plan.go
pkg/types/meta.go
pkg/types/request.go
pkg/types/types.go

Fixes #
```release-note
```
```docs
```

Add cloudnative components API supported

---

pkg/controller/plan/plan.go

Fixes #
```release-note
```
```docs
```

修复plan任务不存在时显示完成的bug

---

pkg/controller/plan/plan.go
pkg/controller/plan/plan_config.go
pkg/types/types.go
template/globals.go

Fixes #
```release-note
```
```docs
```

Add EnablePublicIp for kubernetes configs

---

pkg/controller/plan/plan.go
pkg/controller/plan/plan_config.go
pkg/controller/plan/render.go
pkg/types/types.go
template/globals.go

Fixes #
```release-note
```
```docs
```

Complete Haproxy and KeepAlived API supported

---

template/globals.go

Fixes #
```release-note
```
```docs
```

Fix the empty KeepalivedVirtualRouterId

---

template/globals.go

/kind optimization
Optimized global template.
```release-note
NONE
```

Optimized global template

---

install.md

Fixes #
```release-note
```
```docs
```

Add openEuler22.03 and  rocky9.2  into install.md

---

api/server/errors/errors.go
api/server/httputils/httputils.go
api/server/middleware/authentication.go
api/server/middleware/authorization.go
cmd/app/config/config.go

/kind feature
Deliver user object with gin context.
```release-note
NONE
```

Deliver user object with gin context

---

pkg/client/task.go
pkg/controller/plan/plan_task.go

Fixes #
```release-note
```
```docs
```

Optimise task cache sync by WaitForCacheSync

---

pkg/controller/cluster/cluster.go
pkg/db/model/cluster.go
pkg/types/types.go

Fixes #
```release-note
```
```docs
```

新增容器服务状态更新API

---

pkg/controller/cluster/cluster.go
pkg/db/model/cluster.go
pkg/types/types.go

Fixes #
```release-note
```
```docs
```

Add ClusterStatus supported

---

.github/workflows/ci.yml
install.md

Fixes #
```release-note
```
```docs
```

新增部署驱动镜像操作步骤

---

api/server/router/cluster/cluster.go
api/server/router/cluster/cluster_routes.go
config.yaml
pkg/client/ws.go
pkg/controller/cluster/cluster.go
pkg/types/types.go

Fixes #
```release-note
```
```docs
```

Add watch pod logs API supported

---

api/server/middleware/audit.go
api/server/router/audit/audit.go
pkg/db/model/audit.go

Fixes #
```release-note
```
```docs
```

Fix the audit API bugs

---

api/server/httputils/httputils.go
api/server/middleware/audit.go
api/server/router/user/user_routes.go
pkg/controller/user/user.go
pkg/db/model/audit.go
pkg/types/request.go
pkg/types/types.go

/kind feature
Optimized audit: processing asynchronously. It's unnecessary waiting.
```release-note
NONE
```

Optimized audit

---

api/server/router/plan/plan_routes.go

Fixes #
```release-note
```
```docs
```

Update system support version

---

api/server/router/plan/plan.go
api/server/router/plan/plan_routes.go
api/server/router/plan/task_routes.go
pkg/controller/plan/plan.go
pkg/controller/plan/plan_task.go
pkg/controller/plan/worker.go
pkg/db/plan.go
pkg/util/container/container.go

Fixes #
```release-note
```
```docs
```

支持实时获取plan部署日志

---

cmd/app/server.go
pkg/controller/plan/plan.go
pkg/controller/plan/worker.go

Fixes #
```release-note
```
```docs
```

修复 pixiu 异常退出后的任务状态

---

api/server/router/cluster/cluster.go
api/server/router/cluster/informer.go
pkg/client/cache.go
pkg/controller/cluster/cluster.go
pkg/controller/cluster/informer.go
pkg/controller/plan/plan.go
pkg/controller/plan/worker.go

Fixes #
```release-note
```
```docs
```

支持k8s多集群缓存功能

---

api/server/router/cluster/informer.go
pkg/controller/cluster/cluster.go
pkg/controller/cluster/informer.go
pkg/types/meta.go
pkg/types/request.go

Fixes #
```release-note
```
```docs
```

Add page options supported

---

pkg/controller/cluster/informer.go

Fixes #
```release-note
```
```docs
```

Add deploymente page list supported

---

pkg/controller/cluster/informer.go
pkg/types/meta.go

Fixes #
```release-note
```
```docs
```

Optimise offset func

---

api/server/router/cluster/informer.go
pkg/controller/cluster/informer.go
pkg/types/request.go

Fixes #
```release-note
```
```docs
```

支持获取所有namespace资源

---

api/server/middleware/audit.go
pkg/db/model/audit.go
pkg/db/model/pixiu/model.go

/kind feature
Add request ID to audit record.
```release-note
NONE
```

Add request ID to audit record

---

pkg/controller/cluster/cluster.go
pkg/controller/controller.go
pkg/db/cluster.go
pkg/db/model/pixiu/model.go
pkg/db/model/rbac.go
pkg/db/user.go

/kind feature
Create and delete related policy when creating and deleting cluster.
```release-note
NONE
```

Create and delete related policy with cluster handling

---

pkg/jobmanager/cluster_syncer.go

Fixes #
```release-note
```
```docs
```

Complete cleanLister for cluster sync

---

api/server/httputils/httputils.go
api/server/middleware/authorization.go
cmd/app/options/options.go
pkg/controller/cluster/cluster.go
pkg/controller/user/user.go
pkg/controller/util/util.go
pkg/db/cluster.go
pkg/db/model/rbac.go
pkg/db/model/rbac_test.go
pkg/db/options.go
pkg/util/util.go
pkg/util/util_test.go

/kind feature
User can list objects created by himself only.
If the user is admin/root(has specific group policy), he can list all clusters.

Isolate cluster resources for users

---

hack/tools/licfmt/licfmt.go

/kind bug
The licfmt tool supports CR(Windows editor) now.
```release-note
NONE
```

The licfmt tool supports CR(Windows) now

---

pkg/client/cache.go
pkg/controller/cluster/informer.go

Fixes #
```release-note
```
```docs
```

add sts indexer supported

---

pkg/client/cache.go
pkg/controller/cluster/cluster.go
pkg/controller/cluster/informer.go

Fixes #
```release-note
```
```docs
```

add cronJobCache

---

pkg/controller/cluster/informer.go

Fixes #
```release-note
```
```docs
```

优化 batchv1 包的命名

---

api/server/middleware/log.go
api/server/middleware/middleware.go
cmd/app/config/config.go
cmd/app/options/options.go
pkg/jobmanager/audit_cleaner.go
pkg/jobmanager/cluster_syncer.go
pkg/jobmanager/context.go
pkg/jobmanager/manager.go
pkg/util/log/log.go

/kind feature
Add a log util, and enable/disable SQLs log with config:
```yaml
default:
log_format: json
log_sql: true # false
```
```release-note
NONE
```

Add a log util

---

pkg/client/cache.go
pkg/controller/cluster/cluster.go
pkg/controller/cluster/informer.go

Fixes #
```release-note
```
```docs
```

add jobCache

---

api/server/router/cluster/informer.go
pkg/controller/cluster/cluster.go
pkg/controller/cluster/informer.go
pkg/types/request.go
pkg/types/types.go

Fixes #
```release-note
```
```docs
```

add pod search function

---

pkg/controller/cluster/cluster.go
pkg/controller/plan/plan.go
pkg/jobmanager/cluster_syncer.go

Fixes #
```release-note
```
```docs
```

修复 job manager 重置集群状态异常

---

pkg/controller/cluster/informer.go
pkg/controller/cluster/util.go

Fixes #
```release-note
```
```docs
```

Optimise listObjects funcs

---

api/server/middleware/authentication.go
pkg/db/user.go

/kind bug
Considered all as root user when running in debug mode.
Fixes #525
**The root user is the first user with root role in database.**
```release-note
NONE
```

Considered all as root user when running in debug mode

---

pkg/controller/auth/auth.go
pkg/controller/user/user.go
pkg/controller/util/util.go

/kind feature
Query group binding policy by condition.
```release-note
NONE
```

Query group binding policy by condition

---

docs/sql.md
pkg/db/model/cluster.go

Fixes #
```release-note
```
```docs
```

 fix addCluster failed

---

pkg/controller/plan/plan.go
pkg/controller/plan/plan_node.go

Fixes #
```release-note
```
```docs
```

Fix the update node attr failed

---

pkg/controller/plan/render.go
pkg/util/util.go

Fixes #
```release-note
```
```docs
```

修复节点私钥登陆问题

---

api/server/middleware/log.go
config.yaml
pkg/jobmanager/audit_cleaner.go
pkg/jobmanager/cluster_syncer.go
pkg/jobmanager/context.go
pkg/jobmanager/manager.go
pkg/util/log/log.go

/kind feature
Providing 3 log levels: error, info and debug.
The default log level is `info`.
```release-note
NONE
```

Providing 3 log levels: error, info and debug

---

api/server/errors/errors.go
api/server/router/auth/auth.go
api/server/router/auth/auth_routes.go
pkg/controller/auth/auth.go
pkg/controller/util/util.go
pkg/types/request.go

/kind feature
Add a group binding create API, which binds user to specific group.
route: `/pixiu/auth/binding`
method: `POST`
Calling API like `curl` command here:
```bash
curl -H 'Authorization: Bearer '${token}'' -X POST http://127.0.0.1:8090/pixiu/auth/binding \
-d '{"user_id": 4, "group_name": "root"}'
```

Add a group binding create API

---

hack/update-image.sh

Fixes #
```release-note
```
```docs
```

Create update-image.sh for quick started

---

api/server/httputils/httputils.go
api/server/middleware/audit.go
api/server/middleware/log.go

/kind feature
1. Deliver the response code with context.
2. Reducing the JSON unmarshal expense of audit middleware.
3. Optimized log output:
```log
{"client_ip":"127.0.0.1","error":"密码错误","latency":"9822113µs","level":"error","method":"POST","msg":"FAIL","request_id":"20240914134932-012927","response_code":401,"time":"2024-09-14T13:49:42.029445472+08:00","uri":"/pixiu/users/login"}
```
```
NONE
```

Deliver response code with context

---

pkg/controller/plan/plan_task.go

Fixes #
```release-note
```
```docs
```

修复读取部署任务日志异常问题

---

api/server/middleware/audit.go

Fixes #
```release-note
```
```docs
```

Some modifications to audit

---

api/server/router/audit/audit_routes.go
pkg/controller/audit/audit.go
pkg/db/audit.go

Fixes #
```release-note
```
```docs
```

Add page options for audit API

---

.github/workflows/docker-image.yml
Dockerfile-aio

Fixes #
```release-note
```
```docs
```

修复构建aio镜像失败问题

---

go.mod

Fixes #
```release-note
```
```docs
```

Bump go version to 1.17

---

config.yaml
docker/start.sh
install.md

Fixes #
```release-note
```
```docs
```

简化镜像启动依赖配置

---

.github/workflows/ci.yml
.github/workflows/docker-image.yml
install.md

Fixes #
```release-note
```
```docs
```

修复 stable 分支ci未触发问题
